### PR TITLE
Support Symfony 6 / Laravel 9

### PR DESCRIPTION
**Pull request by davejamesmiller**

### CODE REVIEW

**Comment by beganovich** [comment]
Hey, thanks for the contribution! 

I was wondering if we bump all Symfony components to 6.0, is the minimum PHP gonna be 8 or 8.1?

**Comment by davejamesmiller** [comment]
It would be 8.0.2 I think (https://github.com/symfony/console/blob/v6.0.0/composer.json#L19)... Do you want to drop 5.x support instead of supporting both?

**Comment by beganovich** [comment]
No, we need to keep PHP 7.4 at least. 
One more thing, this is my first time seeing `^5.2|^6.0`. Is Composer gonna pick 5.4 when it doesn't meet requirements for 6.0?

**Comment by davejamesmiller** [comment]
I believe so.

**Comment by beganovich** [comment]
Awesome, thank you for the contribution :+1:

**Comment by beganovich** [comment]
I had a better look at this and I think it would be better if we tag 2.0 with Symfony 6 components only. This will require php-cs-fixer update also (2.x doesn't work with Symfony 6.x components).

That said I will keep 1.x in another branch and keep it supported for some time now.

Do you have time to PR Symfony 6-only version to master?

**Comment by davejamesmiller** [comment]
Done.

I also simplified `"php": "^8.0|^8.1"` to just `"php": "^8.0"`, because that already means `>=8.0 <9.0`.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by beganovich** [comment]
Awesome, thank you so much for contribution :+1:

**Comment by davejamesmiller** [comment]
Thank you for the package. 👍🏻

**Pull request merged**
