### PR TITLE
Add FreeBSD Support.  Add console command to convert HTML to PDF.

### PR DESCRIPTION
**Pull request by phpdave11**

### CODE REVIEW

**Comment by beganovich** [comment]
Hey there!

Thanks for this. Looks awesome. Question: is it not possible to get locally downloaded Chromium with BSD? Only system-wide?

**Comment by phpdave11** [comment]
It may be possible, but a chromium binary is not offered by the download-chromium.appspot.com site.  They only support the following platforms:

SUPPORTED PLATFORMS: 
Chromium for Windows x86
Chromium for Windows x64
Chromium for Mac
Chromium for Linux x86
Chromium for Linux x64
Chromium OS for Linux
Chromium for Android

The changes I made to support FreeBSD will just use the version of Chrome that has been installed to the system.  If it's not installed, then you'll get the following exception:  "Browser binary not found. Make sure you download it or set using setChromiumPath()."

**Comment by beganovich** [comment]
All right, thanks for the clarification.

You have listed chrome as a binary endpoint, is it usual for BSD people to install Chrome or Chromium? Will 'chrome' binary work for Chromium users as well?

Next thing, I think there should be a modification in the DownloadChromiumCommand that will check if it's BSD and if so, return command failure, otherwise, the app will try to download something non-existing from AppSpot (will try to download BSD version from AppSpot which doesn't exist).

**Comment by phpdave11** [comment]
Google doesn't support FreeBSD directly when it comes to Chrome.  Typically FreeBSD users will install [Chromium](https://www.freshports.org/www/chromium) which is installed locally to /usr/local/bin/chrome

**Comment by beganovich** [comment]
Thank you so much for the pull request!

@all-contributors please add @phpdave11 for code

**Comment by beganovich** [comment]
Thank you so much for the pull request! 🎉

**Pull request merged**
