### PR TITLE
add laravel usage example

### LINKED ISSUE #23: Add Laravel usage example with templates
Really nice package, found it very useful in my Laravel app.

What can be added is passing compiled template HTML string into `setHtml()` method.

```php
$snappdf = new \Beganovich\Snappdf\Snappdf();

$fields = [...];

// Render method returns HTML string (template compile)
$html = view('pdf.warranty', compact('fields'))->render();

$pdf = $snappdf
    ->setHtml($html)
    ->save('/path/to/your/file.pdf');
```

PR will be submitted.

### PR DESCRIPTION
**Pull request by kallefrombosnia**
Resolves #23

### CODE REVIEW

**Comment by beganovich** [comment]
Thank you for the contribution 👍

**Comment by davejamesmiller** [comment]
FYI, you don't actually need to call `->render()` manually because views implement `__toString()` which calls it automatically.

https://github.com/laravel/framework/blob/cb2240d84df079ba6b5ed2dd9158e5182100fbd2/src/Illuminate/View/View.php#L434

**Comment by kallefrombosnia** [comment]
Hello, yes true. But `render` is used in my case so that's why I made a PR with that change. If that bugs you, we can open another PR with a typo fix.

The reason why I used it is that `render` throws nicely if something goes wrong which happened in my case.
[render](https://github.com/laravel/framework/blob/cb2240d84df079ba6b5ed2dd9158e5182100fbd2/src/Illuminate/View/View.php#L90-L105)

For basic usage `render` is not needed.

**Comment by davejamesmiller** [comment]
> The reason why I used it is that `render` throws nicely if something goes wrong which happened in my case.

Since PHP 7.4, exceptions should work with `__toString()` as well.

https://wiki.php.net/rfc/tostring_exceptions

**Pull request merged**
